kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraMounts:
  - containerPath: /airflow/local/dags
    hostPath:  /home/username/airflow/dags # Altere para seu caminho
    readOnly: true
- role: edge-worker
  extraMounts:
  - containerPath: /airflow/local/dags
    hostPath:  /home/username/airflow/dags # Altere para seu caminho
    readOnly: true
- role: airflow
  extraMounts:
  - containerPath: /airflow/local/dags
    hostPath:  /home/username/airflow/dags # Altere para seu caminho
    readOnly: true
