apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-edge-worker
  namespace: airflow
  labels:
    app: airflow-edge-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-edge-worker
  template:
    metadata:
      labels:
        app: airflow-edge-worker
    spec:
      containers:
      - name: worker
        image: airflow:2.10.5-edge
        imagePullPolicy: IfNotPresent
        command: ["airflow", "edge", "worker"]
        args: ["--concurrency", "4", "--queue", "worker-1"]
        env:
        - name: AIRFLOW__CORE__EXECUTOR
          value: airflow.providers.edge3.executors.edge_executor.EdgeExecutor
        - name: AIRFLOW__CORE__INTERNAL_API_SECRET_KEY
          value: MmEwYmQ1MWFlYWY4MjA2MGFhZGY0NzY5YmIyMjkzZGE
        - name: AIRFLOW__EDGE__API_ENABLED
          value: "True"
        - name: AIRFLOW__EDGE__API_URL
          value: http://airflow-webserver:8080/edge_worker/v1/rpcapi
        - name: AIRFLOW__EDGE__WORKER_CONCURRENCY
          value: "4"
        - name: AIRFLOW__EDGE__HEARTBEAT_INTERVAL
          value: "10"
        - name: AIRFLOW__EDGE__JOB_POLL_INTERVAL
          value: "5"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: dags
          mountPath: /opt/airflow/dags
      volumes:
      - name: dags
        persistentVolumeClaim:
          claimName: airflow-dags-claim
