kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-dags-claim
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  volumeName: airflow-dags
  storageClassName: standard
  volumeMode: Filesystem
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: airflow-dags
spec:
  capacity:
    storage: 2Gi
  hostPath:
    path:  /airflow/local/dags
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
